[package]
name = "vibro-core"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }

#
# Internal
sal-core = { workspace = true }
testing = { workspace = true }
debugging = { workspace = true }
sal-sync = { workspace = true }

#
# Date & Time
chrono = { version = "0.4", features = ["serde"] }

#
# Serde
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }

#
# Collections

#
# Math
rustfft = "^6.4"
# Alternative https://github.com/smu160/PhastFT (100% Safe Rust, Power of 2 length only, Inbox multithread)


[dev-dependencies]

#
# Collections
slice-ring-buffer = "^0.3"

#
# UI
egui = "^0.35"
egui_plot = "^0.36" # Плагин для двумерных графиков.
# egui_extras = "^0.35" # Набор дополнительных сложных виджетов и утилит.
eframe = "^0.35"
